apiVersion: syn.tools/v1alpha1
kind: Cluster
metadata:
  name: ae3oso
  labels:
    tenant: aezoo6
  annotations:
    tenantslug: bigcorp
spec:
  apiEndpointSecretRef:
    key: k8sapi-ae3oso
    name: default
  displayName: Big Corp. Production Cluster
  slug: prodcluster
  gitRepoTemplate:
    spec:
      apiSecretRef:
        key: my-api-secret
        name: default
      deployKeys:
      - type: ssh-ed25519
        key: AAAA...
        writeAccess: true
  tenantRef:
    name: aezoo6
    namespace: default
  tokenLifeTime: 4h
  facts:
    distribution: openshift3
    cloud: cloudscale
    region: rma1
